services:
  - type: web
    name: olivepizza-owner
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/heartbeat
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        value: https://olivepizza-owner.onrender.com
      - key: MAIN_SITE_BACKEND_URL
        value: https://olive-pizza.onrender.com
      - key: RENDER_PUBLIC_URL
        value: https://olivepizza-owner.onrender.com
